### PR TITLE
remove window title credits >:(

### PR DESCRIPTION
**Pull request by denisapain**
do NOT put credits in the window title please, make it a config option, with this pull I am removing it

### CODE REVIEW

**Comment by SpecKeef** [comment]
Mad

**Comment by denisapain** [comment]
> Mad

yeah... i'm mad that your crediting like that, no other plugin does it

im trying to compile it without the window titile but i cant even compile your original crystal github (this) so yeah

pls merge pls merge pls pls pls

**Comment by 9x00** [comment]
Give me a girls discord and i will remove it

**Comment by denisapain** [comment]
> Give me a girls discord and i will remove it

ill try getting you removed from anticope then 💀

**Comment by 9x00** [comment]
Bros Mad 💀

**Comment by SpecKeef** [comment]
ITS A FUCKING WINDOW TITLE

**Pull request closed without merging**
